# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-images:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run: docker buildx create --use --name "$CIRCLE_PROJECT_REPONAME"
      - run: docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 .
  build-and-push:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - checkout
      - run: docker buildx create --use --name "$CIRCLE_PROJECT_REPONAME"
      - run: echo "$DOCKERHUB_ACCESS_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
      - run: docker buildx build --push --tag "$DOCKERHUB_USERNAME/$CIRCLE_PROJECT_REPONAME":latest --platform linux/amd64,linux/arm/v7,linux/arm64 .


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  docker_build:
    jobs:
      - build-images:
          filters:
            branches:
              ignore: master
      - build-and-push:
          context: dockerhub
          filters:
            branches:
              only: master

